server:
  port: 8091
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/gerardoluceroc/microservicios-data-project
          search-paths: config-data
  application:
    name: config-service

